import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { HiMenu, HiX } from 'react-icons/hi'; // Ícones de menu e fechar
import psiLogo from '../assets/logo.png'; // Importe a logo
export function Header() {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    return (_jsxs("header", { className: "fixed left-0 top-0 z-50 w-full bg-white shadow-md", children: [_jsxs("div", { className: "mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8", children: [_jsx("div", { className: "text-xl font-bold", children: _jsx("img", { src: psiLogo, alt: "logotipo da psi", className: "h-10" }) }), _jsx("div", { className: "md:hidden", children: _jsx("button", { onClick: () => setIsMenuOpen(!isMenuOpen), className: "text-2xl text-gray-700", children: isMenuOpen ? _jsx(HiX, {}) : _jsx(HiMenu, {}) }) }), _jsxs("nav", { className: "hidden space-x-6 md:flex", children: [_jsx(Link, { to: "/", className: "text-gray-700 hover:text-red-600", children: "In\u00EDcio" }), _jsx(Link, { to: "/services", className: "text-gray-700 hover:text-red-600", children: "Servi\u00E7os" }), _jsx(Link, { to: "/who-we-are", className: "text-gray-700 hover:text-red-600", children: "Quem Somos" }), _jsx(Link, { to: "/clients", className: "text-gray-700 hover:text-red-600", children: "Clientes" }), _jsx(Link, { to: "/contact", className: "text-gray-700 hover:text-red-600", children: "Contato" })] }), _jsx("div", { className: "ml-4 hidden md:block", children: _jsx("button", { className: "rounded-full bg-red-600 px-4 py-2 text-white", children: "Entrar em contato" }) })] }), isMenuOpen && (_jsx("div", { className: "w-full bg-white shadow-lg md:hidden", children: _jsxs("nav", { className: "flex flex-col space-y-4 p-4", children: [_jsx(Link, { to: "/", className: "text-gray-700 hover:text-red-600", children: "In\u00EDcio" }), _jsx(Link, { to: "/services", className: "text-gray-700 hover:text-red-600", children: "Servi\u00E7os" }), _jsx(Link, { to: "/who-we-are", className: "text-gray-700 hover:text-red-600", children: "Quem Somos" }), _jsx(Link, { to: "/clients", className: "text-gray-700 hover:text-red-600", children: "Clientes" }), _jsx(Link, { to: "/contact", className: "text-gray-700 hover:text-red-600", children: "Contato" }), _jsx("div", { className: "mt-4", children: _jsx("button", { className: "w-full rounded-full bg-red-600 px-4 py-2 text-white", children: "Entrar em contato" }) })] }) }))] }));
}
